### ISSUE TITLE
Crash on startup (1.20.1-forge-47.1.43)

### ISSUE THREAD

**Issue by spunchbop121** [AstralOrdana/BetterBlockSounds#2]
Latest log - https://pastebin.com/AqDN6YGG

**Comment by SAJewers** [comment]
[latest.log](https://github.com/AstralOrdana/BetterBlockSounds/files/12188552/latest.log)

Getting the same issue, but on latest Quilt.

**Comment by Zartrix** [comment]
I guess all three loaders are affected then. Getting the same issue on latest Fabric.
[latest.log](https://github.com/AstralOrdana/BetterBlockSounds/files/12188704/latest.log)

**Comment by AstralOrdana** [comment]
fix is in development, use version 0.1.0 for now

**Comment by AstralOrdana** [comment]
fixed for 0.1.2, mixin is not recognized by quilt and fix is not planned
